# Scancl Configuration Options
# 
# Options may be given only in long form. In the config file are present
# only the non-default options. The options format is the same as with
# the cmdline format.
#    Example: option_name=3 or 
#	        option_name=text



# set exit code to 101 if any macro is found
#dmse

#applies smart scan method (default)
smartextensions

# do not check any master boot records
#nombr

# scan all boot records
#allboot

# scan  boot record of given drive
#boot=str

# fix all boot records
#fixallboot

# fix boot record of given drive
#fixboot=str

# applies extlist scan method
#extensionlist

# scan all files
#allfiles

# exclude files or directories from scan
#exclude=str

# show all scannned files (default: show infected/suspicious only)
#showall

# scan inside archives (default - not scanning inside archives)
#scaninarchive

# do not scan subdirectories (default - scan subdirectories)
#norecursion

# detect other (non-virus but unwanted) software too (type maybe: dial,joke,game,bdc,
# heur-dblext,pck,spr,adspy,all - detect all types(no spaces allowed between types)) the following types are enabled by 
# default: dial,bdc,heur-dblext,adspy
#withtype=dial,bdc,heur-dblext,adspy

# like --withtype, but disable this type
#withouttype=

# language (e.g. en, de)
lang=en

# scan mailbox (warning: may  be time consuming)
#scanmbox

# heuristic level (0 - off, 1 - low, 2 - medium, 3 - high, default - 0)
#heurlevel=0

# archive maximum uncompressed size in bytes (0 - no size restriction, default - 1GB,
# maximum accepted limit - 4GB)
#archivemaxsize=1GB

# archive maximum recursion level (0 - unlimited recursion, default - 10)
#archivemaxrecursion=10

# archive maximum compression ratio (0 - unlimited, default - 250)
#archivemaxratio=250

#do not follow symbolic links (default - follow symbolic links)
#nolinks

# scan only root filesystem (default - scan all filesystems)
#onefs

# subdirectories maximum recursion level (0 - no recursion, default - unlimited)
#subdirmaxlevel=

# action for infected files (ask, clean, move, rename, delete, delete-archive,
# delete-mailbox, ignore, default - ignore)
#defaultaction=ignore

# action for suspicious files (ask, clean, move, rename, delete, delete-archive,
# delete-mailbox, ignore, default - ignore)
#suspiciousaction=ignore

# extension appended to renamed files
#renameext=vir

# verbose log mode
#verboselog

# display color messages (default - not colored messages)
#colors

# no information are displayed
#quiet

# do not display scan statistics (default - display detailed scan statistics)
#nostats

# log file (default - log to stdout)
#log=str

# append to log file (default - truncate log file)
#logappend

# quarantine directory (default - $(bindir)/quarantine)
#quarantine=str

# directory for temporary files (default - system temporary directory)
#temp=str
